iger-2023: init
voc/streaming-website pull request #215
Opened 2023-07-17 08:31 UTC by Janik-Haag

Streaming website for [iger-2023](https//fairydust.reisen/)

2023-07-17 16:40 UTC, jbeyerstedt commented on configs/conferences/iger-2023/config.php
> +		'SCHEDULE_NAME' => 'Saal',
Im schedule heißt der doch anders.

2023-07-17 21:03 UTC, jbeyerstedt requested changes

2023-07-17 21:03 UTC, jbeyerstedt commented on configs/conferences/iger-2023/config.php
> +		'STREAM' => 'iger-2023',
Das müsste `s1` sein, da wir Case 1 haben und keinen besonderen Ingest-Endpunkt.

2023-07-18 07:44 UTC, Janik-Haag commented
Should be fine now.

2023-07-18 16:38 UTC, jbeyerstedt approved these changes
LGTM

2023-07-18 18:31 UTC, derchrisuk commented
Hast du das vorher mit ./serve.sh lokal getestet?
Bei mir verzieht sich das CSS komplett.
Sieht so aus als wuerde das less nicht gerendert.

2023-07-18 18:40 UTC, Janik-Haag commented
Bei mir sieht das ganze so aus: 
![image](https://github.com/voc/streaming-website/assets/80165193/12769a11-6538-4776-aa92-c7b69562519f)

Das ist das less vom letzten jahr kopiert.

2023-07-18 18:52 UTC, derchrisuk commented
ich hab kein bock mehr auf diese php scheisse

2023-07-18 18:52 UTC, merged

2023-07-18 18:54 UTC, Janik-Haag commented
jo das ist glaube ich auch ein eol php7 für die streaming seite :skull: