Aalen Geekend November 2023
voc/streaming-website pull request #223
Opened 2023-10-19 17:00 UTC by DO1JLR

Das Hackwerk Aalen veranstaltet anfang November ein [Geekend](https://aalen.space/events/geekend23.html) und würde das gerne auf der VOC Infrastruktur Streamen.

Daher gibt es diese Pull-Request zusammen mit meiner Mail an voc@c3voc.de.

2023-10-22 16:29 UTC, jbeyerstedt requested changes

2023-10-22 16:29 UTC, jbeyerstedt commented on configs/conferences/aalen-geekend-23/config.php
> +		'STREAM' => 's3',
Soweit ich weiß ist Case 3 anderweitig unterwegs. Hier muss der Streaming-Endpoint angegeben werden, der euch angelegt wurde.

2023-10-22 18:01 UTC, DO1JLR commented on configs/conferences/aalen-geekend-23/config.php
> +		'STREAM' => 's3',
Danke für den Hinweis. :kissing_heart: 

Leider habe ich noch keine Antwort auf die Mail bekommen und weiß daher nicht, welcher Streaming-Endpoint das sein wird :innocent:

2023-10-24 21:44 UTC, saerdnaer commented on configs/conferences/aalen-geekend-23/config.php
> +		'STREAM' => 's3',
Eigentlich habt ihr halt seit dem rc3 euren eigenen...

2023-10-25 09:49 UTC, DO1JLR commented on configs/conferences/aalen-geekend-23/config.php
> +		'STREAM' => 's3',
Guter Hinweis. Ich hab die ID ``aalend`` gefunden und sie nun mal eingetragen.

Ich selber bin nicht aus Aalen/vom Hackwerk Aalen, daher wusste ich das leider nicht.
Ich kene auch den Streaming key für den ``aalend`` endpunkt leider *(noch)* nicht.

https://github.com/voc/streaming-website/blob/0131d4aca8c7913d23b26c7a2913ff3b7b1fc20e/configs/archive/jev22/config.json#L212-L221

2023-10-28 18:40 UTC, DO1JLR commented on configs/conferences/aalen-geekend-23/config.php
> +		'STREAM' => 's3',
Update: Streaming key für aalend ist uns nun bekannt. Vielen Dank schonmal

2023-10-30 20:44 UTC, derchrisuk commented
Wenn ich das versuche lokal zu testen fliegt mir das PHP um die ohren mit nem 500 fehler

2023-10-30 22:23 UTC, DO1JLR commented
I merged the master branch to this branch and now on my local test version it is working.
Could you please try again @derchrisuk

2023-10-30 23:37 UTC, derchrisuk commented
LGTM

2023-10-30 23:38 UTC, merged